ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Caps_Lock: noop
    Control_L: noop
    Control_R: noop
    Eisu_toggle: clear
    Shift_L: commit_code
    Shift_R: commit_code
config_version: 0.36.custom.4175035758
customization: 4175035758
key_binder:
  bindings:
    - {accept: "Shift+space", toggle: full_shape, when: always}
    - {accept: minus, send: Page_Up, when: has_menu}
    - {accept: equal, send: Page_Down, when: has_menu}
    - {accept: comma, send: Page_Up, when: has_menu}
    - {accept: period, send: Page_Down, when: has_menu}
    - {accept: "Control+p", send: Up, when: composing}
    - {accept: "Control+n", send: Down, when: composing}
    - {accept: "Control+b", send: Left, when: composing}
    - {accept: "Control+f", send: Right, when: composing}
    - {accept: "Control+a", send: Home, when: composing}
    - {accept: "Control+e", send: End, when: composing}
    - {accept: "Control+d", send: Delete, when: composing}
    - {accept: "Control+k", send: "Shift+Delete", when: composing}
    - {accept: "Control+h", send: BackSpace, when: composing}
    - {accept: "Control+g", send: Escape, when: composing}
    - {accept: "Control+bracketleft", send: Escape, when: composing}
    - {accept: "Alt+v", send: Page_Up, when: composing}
    - {accept: "Control+v", send: Page_Down, when: composing}
menu:
  page_size: 9
punctuator:
  half_shape:
    "!": "！"
    "\"": {pair: ["“", "”"]}
    "$": "￥"
    "'": {pair: ["‘", "’"]}
    ",": "，"
    .: "。"
    "/": "/"
    ":": "："
    ";": "；"
    "<": "《"
    ">": "》"
    "?": "？"
    "[": "【"
    "\\": "、"
    "]": "】"
    "^": "……"
    _: "——"
    "|": "·"
recognizer:
  patterns:
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
    uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
    url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$"
schema_list:
  - schema: luna_pinyin_simp
  - schema: luna_pinyin_fluency
  - schema: double_pinyin_flypy
  - schema: wubi_pinyin
  - schema: luna_pinyin_tw
switcher:
  caption: "〔方案选单〕"
  hotkeys:
    - "Control+grave"